spring:
  kafka:
    bootstrap-servers: localhost:9092
    #bootstrap-servers: localhost:9092
app:
  topic:
    foo: foo.t

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.yiibai: DEBUG
